'use strict';

angular.module('EcossentialsApp')
  .controller('PPerksCtrl', function ($scope) {
    $scope.perks = [
	    {name:'The Ecossentials Project 100% Recycled Sticker', cost:10, details:'It\'s a small item with a big message. Show everyone that it is possible to find goods you can feel good about, that you share the values that Ecossentials has been built on, with this unique sticker.', claimed:3, available:4, url:"/grow"}, 
	    {name:'The Ecossentials Project Tote Bag', cost:25, details:'Carry all your reused containers full of bulk organic foods home in a unique tote bag that demonstrates your dedication to your community, world, and family. Of course it\'s made of sustainable fabric, and printed locally. Everyone wins!', claimed:21, available:31, url:"/grow"},
	    {name:'The Ecossentials Project Apron & More', cost:75, details:'Just like our tote bags, these aprons are sustainably made by people paid fairly, using fabric that is good for our environment. It also comes with a collection of all of our favourite recipes, the tried-and-true, healthy, delicious foods that our customers and staff all use, including plenty of excellent recipes for those with allergies and dietary restrictions. We’ll also include a coupon for 15% off your first purchase of bulk foods from our new store. This is a great opportunity to stock up, at a discount, on everything you’ll need when you break-in your apron!', claimed:3, available:4, url:"/grow"}, 
	    {name:'Ecossentials Tote Bag full of Sustainable Products', cost:100, details:'Get our awesome, Ecossentials Project tote bag, filled with a coupon to come in and get a jar of the local preserves of your choice, a Moe’s Hemp Power Bar, one of the Ecossentials Project stickers mentioned above, and a locally made greeting card, in case you decide to give these as a gift to a lucky friend. This is also a handy, mail-able choice for anyone who would like to be involved but is too far away to come to the store.', claimed:21, available:31, url:"/grow"},
	    {name:'Spring Pre-Shop Event Ticket', cost:125, details:'This ticket invites you to Ecossentials the night before our sustainable Spring clothing collection goes onto the floor. Be among the first to choose from the full range of our latest clothing selections. There will be drinks, music, and snacks by Carol, door prizes, as well as a 10% discount off anything you purchase or order that night, which could add up to big savings! We’ll also have our catalogues out, along with catalogues from designers we’re considering bringing in. We’ll be discussing what kinds of clothes you\'d like to see in Ecossentials in the future, so this is a chance for you to help build the Sustainable Clothing department into exactly what you’d like it to be. If you love to shop for sustainable, ethical, innovative, and local clothing in Powell River, we\'d love to have you involved in the join us for what is sure to be a fun night!', claimed:3, available:4, url:"/grow"}, 
	    {name:'Gala Grand Opening Event Ticket', cost:150, details:'Growth for Ecossentials means big things for Powell River, and the local people who produce quality goods, and that\'s worth celebrating! Join us for an exclusive gala event, hosted in our new, bigger, better Ecossentials. Be among the first to see the new store, visit with the staff, producers, artisans, and customers, a community of progressive people who know that the choices we make can make a difference. You can expect decadent organic and local foods prepared by Carol in our cafeteria, drinks, music, and hugs all around. We\'ve all got a lot to be proud of. We would love for you to join us on this very special night, so we can party and thank you in style. This event will also celebrate the unveiling of our Founders’ Steps, where we will publicly recognize all of Ecossentials’ biggest supporters, including you!', claimed:21, available:31, url:"/grow"},
	    {name:'Biodegradably Clean', cost:200, details:'Get set up with your own comprehensive collection of biodegradable, hard-working, Canadian- made cleaners. Includes a limited edition Ecossentials tote bag filled with bottles of our all purpose cleaner, ceramic cleaner, citrus-based degreaser, laundry soap, and dish soap. We will also add a bottle of our natural shampoo, formulated exclusively for us by a lab in Vancouver. When your bottles get empty, just bring them in and we will be happy to refill them for you. To top it off this perk includes professional cleaning by Extreme Clean, Powell River\'s locally owned and operated commercial, automotive and residential cleaners, who use these same high quality, biodegradable cleaning products.', claimed:3, available:4, url:"/grow"}, 
	    {name:'Carol\'s Soup of the Month club', cost:250, details:'In our cafeteria, Carol will be offering her fresh, delicious soups that we know and love from her days in the Flying Yellow Breadbowl. If you enjoyed her soups before, you can imagine how excited we are to enable her to offer them to our community again! This membership card will entitle you to a full jar of enough nourishing, wholesome soup to feed two adults, or filling sides for four, each month for a year. Enjoy a different variety each month, using quality ingredients, skillfully prepared in our on-site commercial kitchen. And we’ll also include one of our locally printed, sustainable tote bags for you to take them home in, along with a ticket to our exclusive Gala Grand Opening Event!', claimed:21, available:31, url:"/grow"},
	    {name:'Eco-friendly birthday party supplies', cost:300, details:'Includes sustainable, ethical, plastic-free goodie bags for 8, recipe and ingredients for a delicious organic birthday cake, (and don’t worry, many substitutions available for those with food or gluten allergies) along with some yummy, healthy snacks for the party, and a $25 gift certificate for the birthday child to spend in our eco toy section! And it all comes in one of our limited edition tote bags, mentioned above. You’ll also get a ticket to our Gala Grand Opening Event, so we can celebrate the growth of Ecossentials with you!', claimed:3, available:4, url:"/grow"}, 
	    {name:'Regular sized Sunshine Organics bin, every week for a month', cost:400, details:'Have you ever thought about signing up for Sunshine Organics\' organic produce and grocery bins? Or, maybe you have a friend or family member you\'d like to send a gift of fresh organic produce? Well, here is a great opportunity. Once you log in to www.sunshineorganics.ca you can select from organic and local produce. Then we\'ll deliver your selections to the address of your choice, either your own or a friend’s, in Powell River or the Comox Valley. So, even if you are ordering from across the Straight, we want you to know that we look forward to sharing Ecossentials with you when you visit the Sunshine Coast. And in addition to four bins full of local and organic produce, you\'ll also get our limited edition sticker, Ecossentials tote bag, and a ticket to our gala grand opening event mentioned above, as a thank you for your gracious support.', claimed:21, available:31, url:"/grow"},
	    {name:'First meals from the kitchen, exclusive dinner for 6', cost:1000, details:'Those lucky people will enjoy a sumptuous platter of local and organic gourmet foods expertly prepared by the renowned local cook Carol Sigvaldason. You and the 5 lucky people you bring will be among the first to see the menu of all that will be available at our organic cafeteria. You’ll also be the first to sit at the tables, taste the food, and then look around the new store. You\'ll get a full guided tour of the space, including the brand new kitchen where your food is hand-prepared using only the finest ingredients available. It’ll be a chance for us to share our excitement with you over some incredible food and drinks. You’ll also get a ticket to attend our gala event mentioned above. We want to make sure we get to hang out with you, the people who share our pride and excitement in what we are building together as a community.', claimed:3, available:10, url:"/grow"}, 
	    {name:'Private dinner for 10', cost:2500, details:'This perk is truly special. Carol will come to your home and prepare a mouth-watering meal for you and nine of your luckiest friends and family members. You will have the opportunity to work with Carol to develop a menu for your event that features all your favourite ingredients: local meats, cheeses, produce, fair-trade coffee, chocolate, organic spices, grains, and more. Indulge in a night to remember, a gourmet meal to host, professionally cooked to your specific tastes in your own home. This perk also includes one of our limited edition Ecossentials Project aprons, one of our locally printed tote bags, and a collection of the store’s favourite recipes, with a 15% off coupon for your first purchase of bulk foods at our new store, along with two tickets to our grand opening gala, as we would love to have such dedicated supporters there to celebrate with us!', claimed:21, available:31, url:"/grow"}
    ];

  });
